name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm install

      - name: Install frontend dependencies and build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Optional: Add backend build or test steps here
      # - name: Run backend tests
      #   run: npm test

      # Optional: Deploy step (for Render, deployment is usually automatic on push)
      # - name: Deploy to Render
      #   run: echo "Deploy step here if needed"